name:                slipstream
version:             0.1.0.0
github:              "patroclos/slipstream"
license:             MIT
author:              "Joshua Jensch"
maintainer:          "jenschjoshua@gmail.com"
copyright:           "2018 Joshua Jensch"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A bittorrent tool

dependencies:
- base >= 4.7 && < 5
- bifunctors
- bytestring
- either
- parsec
- split
- cryptohash
- uri-encode
- uri-bytestring
- network
- binary
- parallel-io
- mtl
- transformers
- random

library:
  source-dirs: src

executables:
  slipstream-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slipstream

tests:
  slipstream-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slipstream
